# Generated by Django 3.2.5 on 2022-02-02 12:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='COVID_India',
            fields=[
                ('Region', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Total_Cases', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999999999999999)])),
                ('Positive_Cases_Today', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999999999999999)])),
                ('Active_Cases', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999999999999999)])),
                ('Total_Cases_Recovered', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999999999999999)])),
                ('Daily_Cases_Recovered', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999999999999999)])),
                ('Confirmed_Deaths', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999999999999999)])),
                ('Deaths_Per_Day', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999999999999999)])),
                ('Active_Cases_Ratio', models.FloatField()),
            ],
        ),
    ]
